//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kneeboard_Server.Properties {

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kneeboard_Server.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // ── SetupWizardForm ──

        internal static string SetupWizard_Title {
            get { return ResourceManager.GetString("SetupWizard_Title", resourceCulture); }
        }

        internal static string SetupWizard_StepTitle1 {
            get { return ResourceManager.GetString("SetupWizard_StepTitle1", resourceCulture); }
        }

        internal static string SetupWizard_StepTitle2 {
            get { return ResourceManager.GetString("SetupWizard_StepTitle2", resourceCulture); }
        }

        internal static string SetupWizard_StepTitle3 {
            get { return ResourceManager.GetString("SetupWizard_StepTitle3", resourceCulture); }
        }

        internal static string SetupWizard_StepTitle4 {
            get { return ResourceManager.GetString("SetupWizard_StepTitle4", resourceCulture); }
        }

        internal static string SetupWizard_MsfsQuestion {
            get { return ResourceManager.GetString("SetupWizard_MsfsQuestion", resourceCulture); }
        }

        internal static string SetupWizard_AutostartGroup {
            get { return ResourceManager.GetString("SetupWizard_AutostartGroup", resourceCulture); }
        }

        internal static string SetupWizard_SimStartCheckbox {
            get { return ResourceManager.GetString("SetupWizard_SimStartCheckbox", resourceCulture); }
        }

        internal static string SetupWizard_AutoDetect {
            get { return ResourceManager.GetString("SetupWizard_AutoDetect", resourceCulture); }
        }

        internal static string SetupWizard_MinimizedCheckbox {
            get { return ResourceManager.GetString("SetupWizard_MinimizedCheckbox", resourceCulture); }
        }

        internal static string SetupWizard_OnlineNetworks {
            get { return ResourceManager.GetString("SetupWizard_OnlineNetworks", resourceCulture); }
        }

        internal static string SetupWizard_PanelInstallGroup {
            get { return ResourceManager.GetString("SetupWizard_PanelInstallGroup", resourceCulture); }
        }

        internal static string SetupWizard_Back {
            get { return ResourceManager.GetString("SetupWizard_Back", resourceCulture); }
        }

        internal static string SetupWizard_Next {
            get { return ResourceManager.GetString("SetupWizard_Next", resourceCulture); }
        }

        internal static string SetupWizard_Skip {
            get { return ResourceManager.GetString("SetupWizard_Skip", resourceCulture); }
        }

        internal static string SetupWizard_Finish {
            get { return ResourceManager.GetString("SetupWizard_Finish", resourceCulture); }
        }

        internal static string SetupWizard_NotDetectedClick {
            get { return ResourceManager.GetString("SetupWizard_NotDetectedClick", resourceCulture); }
        }

        internal static string SetupWizard_BrowseCommunity {
            get { return ResourceManager.GetString("SetupWizard_BrowseCommunity", resourceCulture); }
        }

        internal static string SetupWizard_OtherPath {
            get { return ResourceManager.GetString("SetupWizard_OtherPath", resourceCulture); }
        }

        // ── InformationForm ──

        internal static string Info_NotDetected {
            get { return ResourceManager.GetString("Info_NotDetected", resourceCulture); }
        }

        internal static string Info_CacheCleared {
            get { return ResourceManager.GetString("Info_CacheCleared", resourceCulture); }
        }

        internal static string Info_CacheClearError {
            get { return ResourceManager.GetString("Info_CacheClearError", resourceCulture); }
        }

        internal static string Info_CacheTitle {
            get { return ResourceManager.GetString("Info_CacheTitle", resourceCulture); }
        }

        internal static string Info_ErrorTitle {
            get { return ResourceManager.GetString("Info_ErrorTitle", resourceCulture); }
        }

        internal static string Info_NavigraphAuthFailed {
            get { return ResourceManager.GetString("Info_NavigraphAuthFailed", resourceCulture); }
        }

        internal static string Info_NavigraphFallbackMsg {
            get { return ResourceManager.GetString("Info_NavigraphFallbackMsg", resourceCulture); }
        }

        internal static string Info_InstallSuccess {
            get { return ResourceManager.GetString("Info_InstallSuccess", resourceCulture); }
        }

        internal static string Info_InstallPartial {
            get { return ResourceManager.GetString("Info_InstallPartial", resourceCulture); }
        }

        internal static string Info_MsfsPanelTitle {
            get { return ResourceManager.GetString("Info_MsfsPanelTitle", resourceCulture); }
        }

        internal static string Info_CommunityFolderTitle {
            get { return ResourceManager.GetString("Info_CommunityFolderTitle", resourceCulture); }
        }

        internal static string Info_NotInstalled {
            get { return ResourceManager.GetString("Info_NotInstalled", resourceCulture); }
        }

        internal static string Info_Installed {
            get { return ResourceManager.GetString("Info_Installed", resourceCulture); }
        }

        internal static string Info_OtherPath {
            get { return ResourceManager.GetString("Info_OtherPath", resourceCulture); }
        }

        // ── KneeboardServer ──

        internal static string Main_FileOpenError {
            get { return ResourceManager.GetString("Main_FileOpenError", resourceCulture); }
        }

        internal static string Main_FileNotFound {
            get { return ResourceManager.GetString("Main_FileNotFound", resourceCulture); }
        }

        // ── SpendenForm ──

        internal static string Spenden_Close {
            get { return ResourceManager.GetString("Spenden_Close", resourceCulture); }
        }

        // ── Language UI ──

        internal static string Info_LanguageLabel {
            get { return ResourceManager.GetString("Info_LanguageLabel", resourceCulture); }
        }

        internal static string Info_LanguageRestartMsg {
            get { return ResourceManager.GetString("Info_LanguageRestartMsg", resourceCulture); }
        }
    }
}
